version: "3"
services:
  review:
    image: kauplan/review2.5
    volumes:
      - $PWD:/work
    entrypoint: /bin/bash -c "cd /work; set -exo; ./link-version; export STARTER_TARGET=ebook; rake pdf;"
