#!/bin/sh
set -euxo

# ln -f cause error if link was already created.
rm -f config.yml
ln config.$ENV_NAME.yml config.yml
rm -f sty/mytitlepage.sty
ln sty/mytitlepage.$LANG_NAME.sty sty/mytitlepage.sty
rm -f sty/starter.sty
ln sty/starter.$LANG_NAME.sty sty/starter.sty
