version: 2
anchors:
  - &build-anchor
    docker:
      - image: kauplan/review2.5
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: create pdf
          command: |
            ln -f "config.${ENV_NAME}.yml" config.yml
            export STARTER_TARGET=ebook; 
            rake pdf
            mv ${BOOK_NAME}.pdf artifact.pdf
      - store_artifacts:
          path: ~/work/artifact.pdf
          destination: pdf
      - persist_to_workspace:
          root: ~/work
          paths:
            - artifact.pdf
  - &deploy-anchor
    docker:
      - image: justincasetech/aws-cli:1.16.186-jq1.6-git
    working_directory: ~/work
    steps:
      - attach_workspace:
          at: ~/work
      - run: aws s3 cp artifact.pdf s3://hiroga-techbookfest/${BOOK_NAME}.pdf --acl public-read
      - run: aws s3 cp artifact.pdf s3://hiroga-techbookfest/${SHARED_UUID}.pdf --acl public-read

jobs:
  build-prod:
    <<: *build-anchor
    environment:
      ENV_NAME: prod
      BOOK_NAME: "amplify-console-in-action"
  deploy-prod:
    <<: *deploy-anchor
    environment:
      ENV_NAME: prod
      BOOK_NAME: "amplify-console-in-action"
      SHARED_UUID: "812bd999-9d8f-4ffd-b463-19053fef9c60"
  build-trial:
    <<: *build-anchor
    environment:
      ENV_NAME: trial
      BOOK_NAME: "amplify-console-in-action-trial"
  deploy-trial:
    <<: *deploy-anchor
    environment:
      ENV_NAME: trial
      BOOK_NAME: "amplify-console-in-action-trial"
      SHARED_UUID: "2d5cec97-3deb-402e-b60c-1be422bb2550"
  build-en:
    <<: *build-anchor
    environment:
      ENV_NAME: en
      BOOK_NAME: "amplify-console-in-action-en"
  deploy-en:
    <<: *deploy-anchor
    environment:
      ENV_NAME: en
      BOOK_NAME: "amplify-console-in-action-en"
      SHARED_UUID: "f0cc31d8-dd22-48e0-a689-13ec6bc8b443"

workflows:
  version: 2
  workflow:
    jobs:
      - build-prod:
          filters:
            branches:
              only: master
            tags:
              only: /deploy/
      - deploy-prod:
          context: hiroga-aws
          filters:
            branches:
              only: master
            tags:
              only: /deploy/
          requires:
            - build-prod
      - build-trial:
          filters:
            branches:
              only: master
            tags:
              only: /deploy/
      - deploy-trial:
          context: hiroga-aws
          filters:
            branches:
              only: master
            tags:
              only: /deploy/
          requires:
            - build-trial
      - build-en:
          filters:
            branches:
              only: master
            tags:
              only: /deploy/
      - deploy-en:
          context: hiroga-aws
          filters:
            branches:
              only: master
            tags:
              only: /deploy/
          requires:
            - build-en
