version: 2
anchors:
  - &build-anchor
    docker:
      - image: kauplan/review2.5
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: create pdf
          command: |
            ln -f "config.${ENV_NAME}.yml" config.yml
            export STARTER_TARGET=ebook; 
            rake pdf
            mv ${BOOK_NAME}.pdf artifact.pdf
      - store_artifacts:
          path: ~/work/artifact.pdf
          destination: pdf
      - persist_to_workspace:
          root: ~/work
          paths:
            - artifact.pdf
  - &deploy-anchor
    docker:
      - image: justincasetech/aws-cli:1.16.186-jq1.6-git
    working_directory: ~/work
    steps:
      - attach_workspace:
          at: ~/work
      - run: aws s3 cp artifact.pdf s3://hiroga-techbookfest/${BOOK_NAME}.pdf --acl public-read
      - run: aws s3 cp artifact.pdf s3://hiroga-techbookfest/${BOOK_UUID}.pdf --acl public-read

jobs:
  build-prod:
    <<: *build-anchor
    environment:
      ENV_NAME: prod
      BOOK_NAME: "amplify-console-in-action"
      BOOK_UUID: "812bd999-9d8f-4ffd-b463-19053fef9c60"
  deploy-prod:
    <<: *deploy-anchor
    environment:
      ENV_NAME: prod
      BOOK_NAME: "amplify-console-in-action"
      BOOK_UUID: "812bd999-9d8f-4ffd-b463-19053fef9c60"

workflows:
  version: 2
  workflow:
    jobs:
      - build-prod:
          filters:
            branches:
              only: master
            tags:
              only: /deploy/
      - deploy-pord:
          context: hiroga-aws
          filters:
            branches:
              only: master
            tags:
              only: /deploy/
          requires:
            - build-prod
