name: Deploy

on:
  workflow_call:
    inputs:
      env_name:
        type: string
        description: 'env name'
        required: true
        default: 'prod'
      lang_name:
        type: string
        description: 'lang name'
        required: true
        default: 'ja'
      book_name:
        type: string
        description: 'book name'
        required: true
        default: 'amplify-console-in-action'
      shared_uuid:
        type: string
        description: 'shared uuid'
        required: true
        default: '812bd999-9d8f-4ffd-b463-19053fef9c60'

env:
  ENV_NAME: ${{ inputs.env_name }}
  LANG_NAME: ${{ inputs.lang_name }}
  BOOK_NAME: ${{ inputs.book_name }}
  SHARED_UUID: ${{ inputs.shared_uuid }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xhiroga/review2.5-ssh
    steps:
      - uses: actions/checkout@v2
      - name: create pdf
        run: |
          ./link-version
          export STARTER_TARGET=ebook;
          rake pdf
          mv ${BOOK_NAME}.pdf artifact.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact-pdf
          path: ./artifact.pdf

  upload:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xhiroga/aws-cli-node
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact-pdf
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ap-northeast-1
      - run: aws s3 cp artifact.pdf s3://hiroga-books/amplify-console-in-action/${BOOK_NAME}.pdf --acl public-read
      - run: aws s3 cp artifact.pdf s3://hiroga-books/amplify-console-in-action/${SHARED_UUID}.pdf --acl public-read
