name: Deploy En

on:
  push:
    branches:
      - main

jobs:
  deploy-en:
    uses: ./.github/workflows/deploy.yml
    with:
      env_name: en
      lang_name: en
      book_name: amplify-console-in-action-en
      shared_uuid: f0cc31d8-dd22-48e0-a689-13ec6bc8b443
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
