name: Deploy Trial

on:
  push:
    branches:
      - main

jobs:
  deploy-trial:
    uses: ./.github/workflows/deploy.yml
    with:
      env_name: trial
      lang_name: jp
      book_name: amplify-console-in-action-trial
      shared_uuid: 2d5cec97-3deb-402e-b60c-1be422bb2550
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
